# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created On: ')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated On: ')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published On: ')),
            ],
        ),
    ]
